[gwrite]
default_profile = "custom_plotter"

[gwrite.custom_plotter]
unit = "mm"
document_start = "G92.1\nG10 P0 L2 X0 Y0\nG54\nG90\nG21\nG00 Z1\nG00 X0.0000 Y0.0000\nG4 P0.2\n"
layer_start = "(Start Layer)\n"
line_start = "(Start Block)\n"
segment_first = """G00 Z1
G00 X{x:.4f} Y{y:.4f}
G4 P0.3
G01 Z0 F3500
"""
segment = """G01 X{x:.4f} Y{y:.4f}\n"""
line_end = """G00 Z1
G4 P0.5\n"""
document_end = """G00 Z1
G00 X0.0000 Y0.0000
M2"""
invert_y = true
